### ISSUE TITLE
Question about terminology

### ISSUE THREAD

**Issue by mdbergmann** [orthecreedence/blackbird#26]
Hi.

I'd like to use 'blackbird' instead of creating my own 'future' framework.
But I'm having a few headaches with the terminologies used here.

I.e.: why is it called 'promise'?
As I understand 'futures' and 'promises' is that a 'future' represents a future computation and a 'promise' will fulfill it, or set the value of the future.
Which would mean that 'promise' in this library actually is a 'future' and the 'resolve-fn'/'reject-fn' actually represents the 'promise'.

Also things like 'attach' are quite surprising. I would think that a function name like 'on-complete' or 'on-fulfilled' would be easier to understand.

So my question here would be: what are the chances that some name changes could go into this library if I would create a PR?

**Comment by orthecreedence** [comment]
The library is loosely modeled after the bluebird js library. While I'm not
really actively maintaining the library, I'm not really willing to
introduce large breaking changes because of how it might affect others.

I think an option would be to fork it, or probably better is to wrap
blackbird in your own lib that does whatever naming convention you find
comfortable.

**Comment by mdbergmann** [comment]
I don't know the bluebird js library.
Futures and Promises are in fact quite old.
Most other frameworks I know (Scala, Rust and others) are modelled after the original concepts. Can be rad here: https://en.wikipedia.org/wiki/Futures_and_promises

Anyway. Wrapping might indeed be an option.
